[package]
name = "botw-utils"
description = "A library with various utilities for modding Breath of the Wild"
repository = "https://github.com/NiceneNerd/botw-utils-rust"
documentation = "https://docs.rs/botw-utils"
readme = "README.md"
keywords = ["Nintendo", "Zelda", "gamedev"]
categories = ["game-development", "utilities"]
version = "0.3.1"
authors = ["Caleb Smith <macadamiadaze@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"
serde_json = "1.0.56"
twox-hash = "1.6.0"
yaz0 = "0.1.2"